package:
  name: data-processing-builder
  triggers:
    github-trigger:
      source: /whisk.system/github/webhook
      inputs:
        username: $USERNAME
        repository: lionelvillard/openwhisk-data-processing-cloudant
        accessToken: $GITHUB_TOKEN
        events: push
  rules:
    build:
      trigger: github-trigger
      action: openwhisk-builder/github-webhook